app:
  name: go-study
  version: "0.0.1"
  port: 8080
  log:
    level: INFO
    format: TEXT
  hello:
    api:
      enabled: true
  monitoring:
    trace-url: localhost:4317
  auth:
    enabled: true
    secret-key: "dg@#$egf1df#$7"
database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database-name: hello
kafka:
  host: localhost:9092
  consumers:
    go-study:
      host: localhost:9092
      topic: go-study.hello
      group-id: my-group-1
      qnt-consumers: 10
      trace-enabled: false
      enabled: true
      auto-commit: true
      auto-commit-interval: 2s
      offset-reset: earliest
      async-commit: true
workers:
  hello-producer:
    topic: go-study.hello
    interval-millis: 5000
    max-messages: 5
    enabled: false
