services:
  frontend:
    image: bruno303/planning-poker-frontend:${VERSION}
    container_name: planning-poker-frontend
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - self_hosted

  backend:
    image: bruno303/planning-poker-backend:${VERSION}
    container_name: planning-poker-backend
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - CORS_ALLOWED_ORIGINS=https://planning-poker.bsoapp.net,https://k3s.bsoapp.net/planning-poker
      - API_TRACING_ENABLED=false
      - LOG_LEVEL=DEBUG
    networks:
      - self_hosted

networks:
  self_hosted:
    external: true
    name: self_hosted
