apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-poker-backend
  namespace: staging
  labels:
    app: planning-poker-backend
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planning-poker-backend
      env: staging
  template:
    metadata:
      labels:
        app: planning-poker-backend
        env: staging
    spec:
      containers:
      - name: planning-poker-backend
        image:  bruno303/planning-poker-backend:0.0.30
        env:
        - name: API_TRACING_ENABLED
          value: "true"
        - name: LOG_LEVEL
          value: DEBUG
        - name: TRACE_ENABLED
          value: "true"
        - name: TRACE_OTLP_ENDPOINT
          value: "tempo.monitoring.svc.cluster.local:4317"
        - name: API_CORS_ALLOWED_ORIGINS
          value: https://planning-poker-staging.bsoapp.net
        - name: ENVIRONMENT
          value: staging
        - name: REDIS_HOST
          value: planning-poker-redis.staging.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_PASSWORD
          value: ""
        - name: ADMIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: planning-poker-backend
              key: ADMIN_API_KEY
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
