apiVersion: v1
kind: Service
metadata:
  name: planning-poker-backend-svc
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: planning-poker-backend
    env: staging
  ports:
    - port: 8080
      targetPort: 8080
