apiVersion: v1
kind: Service
metadata:
  name: planning-poker-frontend-svc
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: planning-poker-frontend
    env: staging
  ports:
    - port: 80
      targetPort: 3000
