apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-le-prod
spec:
  acme:
    # Use the staging server for initial testing, then switch to production
    server: https://acme-v02.api.letsencrypt.org/directory
    email: brunooliveira812@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
