apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-config-pv
  namespace: production
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k3s-volumes/homepage/app/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homepage-icons-pv
  namespace: production
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/k3s-volumes/homepage/app/public/icons"
