apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared-sa
  namespace: cloudflare
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudflared-cluster-access
  namespace: cloudflare
rules:
- apiGroups: [""] # Core API group
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudflared-cluster-binding
  namespace: cloudflare
subjects:
- kind: ServiceAccount
  name: cloudflared-sa
  namespace: cloudflare
roleRef:
  kind: ClusterRole
  name: cloudflared-cluster-access
  apiGroup: rbac.authorization.k8s.io
