apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-poker-backend
  labels:
    app: planning-poker-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planning-poker-backend
  template:
    metadata:
      labels:
        app: planning-poker-backend
    spec:
      containers:
      - name: planning-poker-backend
        image:  bruno303/planning-poker-backend:0.0.8
        env:
        - name: API_TRACING_ENABLED
          value: "false"
        - name: LOG_LEVEL
          value: DEBUG
        - name: TRACE_OTLP_ENDPOINT
          value: "tempo.monitoring.svc.cluster.local:4317"
        - name: API_CORS_ALLOWED_ORIGINS
          value: https://planning-poker.bsoapp.net
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
