apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdfding-ingress
  namespace: production
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: book.bsoapp.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pdfding
            port:
              number: 80
