name: Planning Poker Backend Automated Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'planning-poker/**'
      - '!planning-poker/version.txt'
      - '!planning-poker/frontend/**'

env:
  # Base variables
  APP_DIR: planning-poker
  DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/planning-poker-backend

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Calculate and Increment Version
        id: versioning
        run: |
          CURRENT_VERSION=$(cat ${{ env.APP_DIR }}/version.txt)
          echo "Current Version: $CURRENT_VERSION"

          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)

          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
          
          echo "New Version: $NEW_VERSION"
          echo $NEW_VERSION > ${{ env.APP_DIR }}/version.txt
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "The new image tag will be: $NEW_VERSION"

      - name: Commit and Push Version Bump
        if: steps.versioning.outputs.NEW_VERSION != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.APP_DIR }}/version.txt
          git commit -m "[planning-poker-backend] ci: version bump to ${{ steps.versioning.outputs.NEW_VERSION }}
          git push

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.APP_DIR }}
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ steps.versioning.outputs.NEW_VERSION }}
            ${{ env.DOCKER_REPO }}:latest
